### PR TITLE
Add clean DB functionality. Moved Clean cache functionality

### PR DESCRIPTION
**Pull request by pablomendezroyo**
**Main changes**

- Added a new functionality for cleaning the maindb.json in **system > advanced section**
- Moved clean cache functionality to advanced, together with clean maindb
- Added warmings alerting user for the possible consecuences
- Deleted previous clean cache at dappmanager > clean cache

UI result

image

image

### CODE REVIEW

**Comment by dapplion** [comment]
- I would remove the subtitles "CLEAN DATABASE CONTENT" since there is only one item on the card.
- You should mention a little bit what the database contains
- Also, rename them to "Dappmanager database" and "Dappmanager cache"

**Comment by dapplion** [comment]
Both buttons should have a danger variant consistent with their potential bad impact

**Comment by pablomendezroyo** [comment]
> Both buttons should have a danger variant consistent with their potential bad impact

both of them have it

**Comment by dapplion** [comment]
> > Both buttons should have a danger variant consistent with their potential bad impact
> 
> both of them have it

Not here https://github.com/dappnode/DNP_DAPPMANAGER/pull/608/files#diff-b0369bec18f041b2ba0ce391c8e3a877e70f8fb1c32507709cbfb7df8852fa8dR35 the should have `variant="outline-danger"`

**Comment by dapplion** [comment]
@pablomendezroyo bump

**Review by dapplion — APPROVED** [review]

**Pull request merged**
