### PR TITLE
Add Lodestar Prater

### PR DESCRIPTION
**Pull request by alexpeterson91**
Adding lodestar to server mock
Add Lodestar Prater to stakersUI

Tracked in #1194 
# DO NOT Merge yet

## Context

> Provide context of this PR: why it was created? what does it fixes? what new feature does it provides? ...

## Approach

> Define the solution for the issue or feature that this PR aims to fix

### CODE REVIEW

**Comment by alexpeterson91** [comment]
will fix #1194

**Review by pablomendezroyo — APPROVED** [review]

**Comment by pablomendezroyo** [comment]
Whats the status?

**Comment by pablomendezroyo** [comment]
Please, rebase the branch to reduce the amount of commits

**Comment by alexpeterson91** [comment]
> Whats the status?

Status is tracked [here](https://github.com/orgs/dappnode/projects/40/)

Everything has been merged etc except this dappmanager PR and the publication Lodestar prater which needs to be

Everything is ready to go and has been for many months, @dapplion signed off on the Lodestar prater package and its authentication for the web3signer but theres in the last week been many requests to change it.  I requested @dapplion to confirm the parameters and signer authentication config are set correctly but i havnt heard back yet

**Comment by alexpeterson91** [comment]
> Please, rebase the branch to reduce the amount of commits

will do, though i may split this PR up anyway, one to add lodestar to server Mock, another to add lodestar prater

**Comment by alexpeterson91** [comment]
replaced by #1378 and #1377

**Comment by dapplion** [comment]
@alexpeterson91 please check in with Nico to sign off changes

**Pull request closed without merging**
