### PR TITLE
Add .local alias

### PR DESCRIPTION
**Pull request by dapplion**
@3alpha @pablomendezroyo  Do we want to add this?

### CODE REVIEW

**Comment by pablomendezroyo** [comment]
Im not sure what the alias `dappnode.local` would be used for.
As far as a I know it is only used by avahi-daemon.

**Comment by dapplion** [comment]
I though we talked about this week. If a user connects via WIFI or VPN and navigates to this URL so that it still works.

**Comment by pablomendezroyo** [comment]
> I though we talked about this week. If a user connects via WIFI or VPN and navigates to this URL so that it still works.

you right

**Review by pablomendezroyo — APPROVED** [review]

**Comment by Jakic007** [comment]
This needs to be tested on linux machines because there are some configuration files which prevent resolution of .local domains via DNS servers after mDNS has failed.

**Comment by dapplion** [comment]
> This needs to be tested on linux machines because there are some configuration files which prevent resolution of .local domains via DNS servers after mDNS has failed.

Right, that's definitely an issue to take into account. Tho having this on place is worse than having nothing?

**Comment by 3alpha** [comment]
It definitely won't break anything, but I am not sure it will work.

**Comment by dapplion** [comment]
> It definitely won't break anything, but I am not sure it will work.

Do you think It's worth merging? @3alpha

**Comment by 3alpha** [comment]
I'll test it today and get back to you.

**Pull request merged**
