### PR TITLE
Move away from non RFC1918 compliant Network Address

### PR DESCRIPTION
**Pull request by lodotek**

### CODE REVIEW

**Comment by dapplion** [comment]
@3alpha Please can you review?

**Comment by 3alpha** [comment]
It is not going to work like this, because it would break everything. Migration has to be system wide, not just in DAppManager.

**Comment by lodotek** [comment]
Yes of course it will need to be changed everywhere.

**Comment by 3alpha** [comment]
It is not just about changing, but also about migration since all packages need to be updated and that happens in asynchronous fashion. I am closing this PR now and I will open an issue which will deal with this in multistep approach.

**Pull request closed without merging**
