### PR TITLE
Add data send feature

### PR DESCRIPTION
**Pull request by dapplion**
Allow packages to post data to the DAPPMANAGER which will be displayed in the UI.

Example usage:

```
curl -X POST http://my.dappnode/data-send?key=apiKey&data=AAXXAAXXAAXXAAXXAAXXAAXXAAXXAAXXAAXXAAXX
```

The DAPPMANAGER will use the IP of the incoming request to assign the data to an installed package.

Screenshot from 2021-07-13 16-51-06

### CODE REVIEW

**Comment by dapplion** [comment]
Tested and works well

**Review by pablomendezroyo — APPROVED** [review]

**Comment by pablomendezroyo** [comment]
Looks really cool this feature, maybe we should add this somewhere in the docs @tropicar ?

**Comment by dapplion** [comment]
> Looks really cool this feature, maybe we should add this somewhere in the docs @tropicar ?

Yes please! Tho on release

**Review by tropicar — APPROVED** [review]

**Comment by tropicar** [comment]
> > Looks really cool this feature, maybe we should add this somewhere in the docs @tropicar ?
> 
> Yes please! Tho on release

It would be a good idea to add it, I will add it when the release is released

**Pull request merged**
