### PR TITLE
Add proper links to ENV values for Merge

### LINKED ISSUE #1088: For Merge Replace “Api” with “Querying API”
Detailed in dappnode/DAppNode#461 
Replace `API` with `Querying API`
and add API-engine to display endpoint link just as API and endpoint do currently.

### PR DESCRIPTION
**Pull request by alexpeterson91**
## Context
To close #1088 and #1090
> Provide context of this PR: why it was created? what does it fixes? what new feature does it provides? ...
detailed in dappnode/DAppNode#461
## Approach
add by editing the links tsx file
> Define the solution for the issue or feature that this PR aims to fix

### CODE REVIEW

**Comment by alexpeterson91** [comment]
im not sure i did this right please take a look.

**Comment by pablomendezroyo** [comment]
Could you add a engine api to a package in the server mock so we can take a look?
The fastest way of developing in the frontend is interactively through the command `yarn mock-standaolne`

**Review by pablomendezroyo — CHANGES_REQUESTED** [review]
I do not see any link you have add at the bitcoin package in the netlify deployment, please before set the PR in draft until its ready for review

**Comment by alexpeterson91** [comment]
> I do not see any link you have add at the bitcoin package in the netlify deployment, please before set the PR in draft until its ready for review

Sorry I should have marked it as draft when you asked me to add backend and wasn't sure how to test it in my local dev environment.

**Comment by alexpeterson91** [comment]
But I did try adding the links in Bitcoin it just doesn't seem to have worked. The manifest listings and the mock bitcoin package are not the same format. I need to work on it more.

**Comment by pablomendezroyo** [comment]
Sure, let me know if I can help you on this

**Comment by alexpeterson91** [comment]
> Sure, let me know if I can help you on this

Can you look at my commit to the bitcoin.ts file and show me the right format that would reflect the resolution of the manifest file? It's so similar but just not the same way of declaring things and has other priorities and formatting than the a manifest file would. 
Does it need to Just have the API links properties in array format be added or the api lines moved into the links array (if there is one already for the git repo, project homepage, and bugs/issue reporting link) I'm on mobile so I'm not looking at the code right now and I'm going from memory.

**Comment by alexpeterson91** [comment]
moved to #1091

**Pull request closed without merging**
