### PR TITLE
Add Nethermind-xDai to preapproved HTTPS Portal

### PR DESCRIPTION
**Pull request by alexpeterson91**
added nethermind xDai to the preapproved HTTPS portal fixes https://github.com/dappnode/DAppNode/issues/385

### CODE REVIEW

**Review by 3alpha — APPROVED** [review]

**Review by dapplion — CHANGES_REQUESTED** [review]
If you are gonna release xDAI soon you can add the exposable services there in the manifest. Should be equivalent to this PR.

https://github.com/dappnode/DNP_DAPPMANAGER/blob/58163d73466eaa272b41ef00fff7bbec9e35c8c5/packages/dappmanager/src/modules/https-portal/exposable/index.ts#L18

Manifest docs 

https://docs.dappnode.io/developers/manifest-reference#exposable

**Review by bh2smith — APPROVED** [review]
Looks great. Wen merge!?

**Comment by dapplion** [comment]
> How will this or that change affect those who are already running the service? Will this require update and restart?

Both if we ship this in the DAPPMANAGER of the xDAI package just an update will do the trick :)

**Comment by alexpeterson91** [comment]
Do you still want me to update the manifest for nethermind xDai to add the services to the portal?

**Comment by alexpeterson91** [comment]
ok replacement fix via https://github.com/dappnode/DAppNodePackage-nethermind-xdai/pull/21 @dapplion please let me know if this works and I'll close this

**Comment by 3alpha** [comment]
We can close it now and track it in github.com/dappnode/DAppNodePackage-nethermind-xdai/pull/21.

**Comment by alexpeterson91** [comment]
Closed with https://github.com/dappnode/DAppNodePackage-nethermind-xdai/pull/21

**Comment by pablomendezroyo** [comment]
can we close this?

**Comment by alexpeterson91** [comment]
> @alexpeterson91  can we close this?

Last I checked it still wasn't exposing both WS and RPC into the HTTPS portal, using the manifest file in the package could only do one. But this way worked and did both. So idk it's stale but it's not resolved elsewhere so I wouldn't close it until it is resolved somewhere if not here.

**Comment by alexpeterson91** [comment]
fixed by https://github.com/dappnode/DAppNodePackage-nethermind-xdai/pull/51

**Comment by alexpeterson91** [comment]
replaced by https://github.com/dappnode/DAppNodePackage-nethermind-xdai/pull/51

**Pull request closed without merging**
