### PR TITLE
Disable updated button

### PR DESCRIPTION
**Pull request by pablomendezroyo**
Disable button if `isUpdated`

### CODE REVIEW

**Review by 3alpha — APPROVED** [review]

**Review by dapplion — APPROVED** [review]

**Comment by dapplion** [comment]
> I have one comment here. I agree this is confusing to allow the button to be clicked but is there another way to start the setup_wizard from the GUI? Or have all fields been made available in the config tab? I know at one point months back I had to go through the updated button to change profile settings on IPFS but that hasn't been the case in a while now. Just wanna make sure we don't lock ourselves out of a setup wizard.

For installed packages you can see the setup wizard at each package config package. For IPFS, got to UI -> packages -> IPFS -> config (tab)

Can you double check if you can get to the page you expect that way?

> Also question does the version checking work by checking the package IPFS hashes or does it compare the version data?

AFAIK it compares the package semver with the installed semver

**Comment by alexpeterson91** [comment]
@dapplion i dont know if SemVer will work for this, if the semver of a package is higher than currently released it assumes you are updated and running the latest package, even if you're not, downgrading to the latest release wont be possible.  Im not totally sure how each function checks for updated or not but i have found some irregularities with a couple packages on my test machines, where this being released could cause me issues id need to go to GH or the package explorer to grab a hash of the latest release or whatever.  i dont know enough about it but i think this deserves another look and review.

**Comment by dapplion** [comment]
> @dapplion i dont know if SemVer will work for this, if the semver of a package is higher than currently released it assumes you are updated and running the latest package, even if you're not, downgrading to the latest release wont be possible from the UI as is is currently. Im not totally sure how each function checks for updated or not but i have found some irregularities with a couple packages on my test machines, where this being released could cause me issues id need to go to GH or the package explorer to grab a hash of the latest release or whatever. i dont know enough about it but i think this deserves another look and review.

Definitely would need a more in depth review, @alexpeterson91 @pablomendezroyo can you open an issue?

**Comment by pablomendezroyo** [comment]
> > @dapplion i dont know if SemVer will work for this, if the semver of a package is higher than currently released it assumes you are updated and running the latest package, even if you're not, downgrading to the latest release wont be possible from the UI as is is currently. Im not totally sure how each function checks for updated or not but i have found some irregularities with a couple packages on my test machines, where this being released could cause me issues id need to go to GH or the package explorer to grab a hash of the latest release or whatever. i dont know enough about it but i think this deserves another look and review.
> 
> Definitely would need a more in depth review, @alexpeterson91 @pablomendezroyo can you open an issue?

@alexpeterson91 not sure what Im looking for, feel free to open an issue with a very specific detailed problem

**Pull request merged**
