### PR TITLE
Switch from security updates to full upgrade

### PR DESCRIPTION
**Pull request by pablomendezroyo**
The security updates was giving faiure in Buster, also it was requested by many users the ability to do a fill apt `update && apt upgrade` directly from the UI

Consider:
- Relocate the UI script execution location
- Any other suggestion for the `apt-upgrade` command?

cc: @3alpha

### CODE REVIEW

**Review by 3alpha — COMMENTED** [review]
Should this script be renamed to reflect its purpose?

**Comment by pablomendezroyo** [comment]
> Should this script be renamed to reflect its purpose?

good point. Yes, it should be renamed

**Comment by pablomendezroyo** [comment]
> I am having second thoughts about this, maybe we should go this route: https://wiki.debian.org/UnattendedUpgrades

I would consider automatic updates danger for the user, could they break dappnode host in some edge cases? maybe could be something to be automated on demand by the user

**Comment by 3alpha** [comment]
We could think about it and we can merge this for now. Only we need to change UI displays and warning as well.

**Review by dapplion — APPROVED** [review]

**Pull request merged**
